# data/standards.py
#
# Standards overview / comparison data.
# Source basis: ARAI published AIS material and related official
# government/ARAI reference material.
#
# Calculator formulas remain in their respective calculator
# HTML / JS / API implementations.

STANDARDS = {

    "AIS-003": {
        "code": "AIS-003",
        "title": "Automotive Vehicles — Starting Gradeability — Method of Measurement and Requirements",

        "overview": (
            "Specifies the method for measuring and assessing the "
            "starting gradeability capability of an automotive vehicle."
        ),

        "scope": (
            "Covers the test conditions, measurement approach and "
            "calculation used to determine the ability of a vehicle "
            "to start from rest on a specified gradient."
        ),

        "category": "Vehicle Performance",
        "vehicle_type": "Automotive vehicles",

        "purpose": (
            "To establish a consistent method for evaluating the "
            "vehicle's ability to start on an inclined road surface."
        ),

        "applicability": (
            "Relevant to vehicle performance evaluation where starting "
            "gradeability is required as part of the applicable approval "
            "or evaluation procedure."
        ),

        "ev_related": False,
        "formula_available": True,
        "calculator_available": True,

        "key_requirements": [
            "Specified vehicle test condition",
            "Measurement of parameters required for gradeability calculation",
            "Starting gradeability assessment",
            "Extrapolated gradeability assessment where applicable",
        ],

        "test_focus": [
            "Starting on gradient",
            "Vehicle loading condition",
            "Measured test parameters",
            "Gradeability calculation",
        ],

        "revision_history": [
            "AIS-003"
        ],

        "amendments": [],

        "related_standards": [
            "AIS-053",
        ],

        "comparative_study": {
            "primary_role": "Vehicle performance measurement",
            "main_output": "Starting gradeability",
            "engineering_domain": "Vehicle dynamics / performance",
            "best_compared_with": [
                "AIS-040",
                "AIS-041",
            ],
            "comparison_note": (
                "AIS-003 evaluates the ability to start on a gradient, "
                "whereas AIS-040 evaluates driving range and AIS-041 "
                "evaluates power capability."
            ),
        },

        "source": "ARAI AIS publication",
    },


    "AIS-004": {
        "code": "AIS-004",
        "title": "Automotive Vehicles — Requirements for Electromagnetic Compatibility",

        "overview": (
            "Defines electromagnetic compatibility requirements for "
            "automotive vehicles and their relevant electrical/electronic "
            "systems."
        ),

        "scope": (
            "AIS-004 covers electromagnetic emission and immunity "
            "requirements through its applicable parts, addressing "
            "vehicle electromagnetic behaviour and protection against "
            "electromagnetic interference."
        ),

        "category": "Automotive Electronics / EMC",
        "vehicle_type": "Motor vehicles and relevant electrical/electronic systems",

        "purpose": (
            "To limit electromagnetic disturbance generated by vehicles "
            "and ensure that vehicle electrical/electronic systems have "
            "appropriate immunity to external electromagnetic fields."
        ),

        "applicability": (
            "Applicable to vehicles and electrical/electronic systems "
            "within the scope of the relevant AIS-004 part."
        ),

        "ev_related": True,
        "formula_available": True,
        "calculator_available": True,

        "key_requirements": [
            "Electromagnetic emissions",
            "Radiated immunity",
            "Vehicle-level EMC",
            "Electrical/electronic subsystem compatibility",
        ],

        "test_focus": [
            "Radiated emissions",
            "Radiated immunity",
            "Electromagnetic disturbance",
            "Electronic system behaviour",
        ],

        "revision_history": [
            "AIS-004 Part 1",
            "AIS-004 Part 2",
            "AIS-004 Part 3",
            "AIS-004 Part 3 (Rev.1)",
        ],

        "amendments": [
            "Applicable amendments depend on the relevant AIS-004 part."
        ],

        "related_standards": [
            "AIS-038",
            "AIS-048",
            "AIS-071",
            "AIS-156",
        ],

        "comparative_study": {
            "primary_role": "Electromagnetic compatibility",
            "main_output": "EMC compliance",
            "engineering_domain": "Automotive electronics",
            "best_compared_with": [
                "AIS-038",
                "AIS-156",
            ],
            "comparison_note": (
                "AIS-004 addresses electromagnetic compatibility, while "
                "AIS-038 and AIS-156 address broader EV electrical and "
                "functional safety requirements. AIS-004 can therefore "
                "act as an electrical/electronic compatibility layer "
                "within those vehicle safety frameworks."
            ),
        },

        "source": "ARAI AIS publication",
    },


    "AIS-038": {
        "code": "AIS-038",
        "title": (
            "Electric Power Train Vehicles — "
            "Requirements for Construction and Functional Safety"
        ),

        "overview": (
            "Defines requirements for the construction and functional "
            "safety of electric power-train vehicles, including vehicle "
            "electrical safety and rechargeable electrical energy "
            "storage system safety."
        ),

        "scope": (
            "Covers requirements associated with the electric power train "
            "and rechargeable electrical energy storage system (REESS) "
            "for applicable electric vehicles."
        ),

        "category": "EV / Functional Safety",
        "vehicle_type": (
            "Electric power-train vehicles, primarily M and N categories"
        ),

        "purpose": (
            "To establish vehicle-level electrical and functional safety "
            "requirements for electric power-train vehicles."
        ),

        "applicability": (
            "Core electric-vehicle safety standard for the applicable "
            "vehicle categories and approval conditions."
        ),

        "ev_related": True,
        "formula_available": True,
        "calculator_available": True,

        "key_requirements": [
            "Electrical safety",
            "Electric power-train safety",
            "REESS safety",
            "Protection against electric shock",
            "Isolation-related requirements",
            "Functional safety provisions",
        ],

        "test_focus": [
            "Electrical isolation",
            "Protection against electric shock",
            "Water-effect related testing",
            "REESS-related safety",
            "Vehicle functional safety",
        ],

        "revision_history": [
            "AIS-038 (Rev.2)",
            "Amendment 1",
            "Amendment 2",
            "Amendment 3",
            "Amendment 4",
        ],

        "amendments": [
            "Amendments have progressively added or updated requirements "
            "for EV electrical safety, battery/BMS-related provisions "
            "and other safety requirements."
        ],

        "related_standards": [
            "AIS-039",
            "AIS-040",
            "AIS-041",
            "AIS-048",
            "AIS-049",
            "AIS-138",
            "AIS-156",
        ],

        "comparative_study": {
            "primary_role": "Vehicle-level EV safety",
            "main_output": "Electrical and functional safety compliance",
            "engineering_domain": "Electric power train / vehicle safety",
            "best_compared_with": [
                "AIS-048",
                "AIS-156",
            ],
            "comparison_note": (
                "AIS-038 is primarily a vehicle-level EV safety framework "
                "for the applicable M/N vehicle categories. AIS-048 is "
                "focused specifically on traction-battery safety, while "
                "AIS-156 applies specifically to L-category electric "
                "power-train vehicles."
            ),
        },

        "source": "ARAI AIS publication",
    },


    "AIS-039": {
        "code": "AIS-039",
        "title": (
            "Electric Power Train Vehicles — "
            "Measurement of Electrical Energy Consumption"
        ),

        "overview": (
            "Specifies the methodology for measuring electrical energy "
            "consumption of electric power-train vehicles."
        ),

        "scope": (
            "Defines test and measurement procedures used to determine "
            "the electrical energy consumption of applicable electric "
            "vehicles."
        ),

        "category": "EV / Energy Consumption",
        "vehicle_type": (
            "Electric power-train vehicles"
        ),

        "purpose": (
            "To provide a standardized basis for determining electrical "
            "energy consumption."
        ),

        "applicability": (
            "Applicable to electric power-train vehicles subject to the "
            "relevant approval and measurement requirements."
        ),

        "ev_related": True,
        "formula_available": True,
        "calculator_available": True,

        "key_requirements": [
            "Electrical energy measurement",
            "Defined test conditions",
            "Energy-consumption calculation",
            "Capacity/correction considerations where applicable",
        ],

        "test_focus": [
            "Energy consumption",
            "Battery energy measurement",
            "Test distance",
            "Test conditions",
        ],

        "revision_history": [
            "AIS-039",
            "AIS-039 (Rev.1)",
            "Amendments to AIS-039 (Rev.1)",
        ],

        "amendments": [
            "Amendment history should be interpreted together with the "
            "applicable current ARAI publication."
        ],

        "related_standards": [
            "AIS-038",
            "AIS-040",
            "AIS-041",
        ],

        "comparative_study": {
            "primary_role": "Energy-efficiency measurement",
            "main_output": "Electrical energy consumption",
            "engineering_domain": "EV efficiency / testing",
            "best_compared_with": [
                "AIS-040",
                "AIS-041",
            ],
            "comparison_note": (
                "AIS-039 measures how much electrical energy the vehicle "
                "uses. AIS-040 measures how far the vehicle can travel, "
                "while AIS-041 measures power capability. Together they "
                "describe complementary EV performance characteristics."
            ),
        },

        "source": "ARAI AIS publication",
    },


    "AIS-040": {
        "code": "AIS-040",
        "title": (
            "Electric Power Train Vehicles — "
            "Method of Measuring the Range"
        ),

        "overview": (
            "Specifies the method used to determine the driving range "
            "of electric power-train vehicles."
        ),

        "scope": (
            "Defines the test methodology and conditions for measuring "
            "the distance an applicable electric vehicle can travel "
            "using its available electrical energy."
        ),

        "category": "EV / Range",
        "vehicle_type": "Electric power-train vehicles",

        "purpose": (
            "To establish a repeatable method for determining electric "
            "vehicle range."
        ),

        "applicability": (
            "Applicable to electric power-train vehicles for which "
            "range measurement is required."
        ),

        "ev_related": True,
        "formula_available": True,
        "calculator_available": True,

        "key_requirements": [
            "Range test procedure",
            "Specified test conditions",
            "Vehicle operating conditions",
            "Measurement of distance travelled",
        ],

        "test_focus": [
            "Driving range",
            "Battery state of charge",
            "Test cycle",
            "Distance measurement",
        ],

        "revision_history": [
            "AIS-040",
            "AIS-040 (Rev.1):2015",
            "Amendment 1",
            "Amendment 2",
        ],

        "amendments": [
            "Current applicability should be checked against the latest "
            "ARAI publication and notified requirements."
        ],

        "related_standards": [
            "AIS-038",
            "AIS-039",
            "AIS-041",
        ],

        "comparative_study": {
            "primary_role": "EV range measurement",
            "main_output": "Vehicle driving range",
            "engineering_domain": "EV performance",
            "best_compared_with": [
                "AIS-039",
                "AIS-041",
            ],
            "comparison_note": (
                "AIS-040 focuses on distance/range, whereas AIS-039 "
                "focuses on energy consumption. AIS-041 addresses power "
                "capability. These standards therefore measure different "
                "dimensions of EV performance."
            ),
        },

        "source": "ARAI AIS publication",
    },


    "AIS-041": {
        "code": "AIS-041",
        "title": (
            "Electric Power Train Vehicles — Measurement of Net Power "
            "and the Maximum 30 Minute Power"
        ),

        "overview": (
            "Specifies methods for determining the net power and "
            "maximum 30-minute power of electric power-train vehicles."
        ),

        "scope": (
            "Covers measurement procedures for electric drive-train "
            "power capability under specified test conditions."
        ),

        "category": "EV / Power",
        "vehicle_type": "Electric power-train vehicles",

        "purpose": (
            "To provide a standardized method for determining relevant "
            "power characteristics of an electric power train."
        ),

        "applicability": (
            "Applicable where electric power-train net power and "
            "maximum 30-minute power are required for approval or "
            "technical evaluation."
        ),

        "ev_related": True,
        "formula_available": False,
        "calculator_available": False,

        "key_requirements": [
            "Net power measurement",
            "Maximum 30-minute power measurement",
            "Specified test conditions",
            "Power measurement procedure",
        ],

        "test_focus": [
            "Net power",
            "30-minute power",
            "Electric drive train performance",
        ],

        "revision_history": [
            "AIS-041",
            "AIS-041 (Rev.1):2015",
            "Amendment 1",
        ],

        "amendments": [],

        "related_standards": [
            "AIS-038",
            "AIS-039",
            "AIS-040",
        ],

        "comparative_study": {
            "primary_role": "EV power measurement",
            "main_output": "Net power and maximum 30-minute power",
            "engineering_domain": "EV powertrain performance",
            "best_compared_with": [
                "AIS-039",
                "AIS-040",
            ],
            "comparison_note": (
                "AIS-041 measures power capability, AIS-039 measures "
                "electrical energy consumption and AIS-040 measures "
                "range. They are complementary rather than interchangeable."
            ),
        },

        "source": "ARAI AIS publication",
    },


    "AIS-048": {
        "code": "AIS-048",
        "title": (
            "Battery Operated Vehicles — Safety Requirements "
            "of Traction Batteries"
        ),

        "overview": (
            "Specifies safety requirements and associated tests for "
            "traction batteries used in battery-operated vehicles."
        ),

        "scope": (
            "Focuses on traction-battery safety and battery-related "
            "testing for battery-operated vehicles."
        ),

        "category": "EV / Traction Battery Safety",
        "vehicle_type": "Battery-operated vehicles",

        "purpose": (
            "To assess the safety of traction batteries under specified "
            "electrical, mechanical and environmental conditions."
        ),

        "applicability": (
            "Applies to traction batteries used in battery-operated "
            "vehicles within the relevant regulatory scope."
        ),

        "ev_related": True,
        "formula_available": True,
        "calculator_available": True,

        "key_requirements": [
            "Traction battery safety",
            "Electrical safety",
            "Mechanical robustness",
            "Environmental safety",
            "Abnormal-condition testing",
        ],

        "test_focus": [
            "Short circuit",
            "Overcharge",
            "Mechanical testing",
            "Vibration / shock",
            "Environmental conditions",
            "Battery safety behaviour",
        ],

        "revision_history": [
            "AIS-048",
            "Amendment 1",
        ],

        "amendments": [],

        "related_standards": [
            "AIS-038",
            "AIS-049",
            "AIS-156",
        ],

        "comparative_study": {
            "primary_role": "Traction-battery safety",
            "main_output": "Battery safety compliance",
            "engineering_domain": "Battery / REESS safety",
            "best_compared_with": [
                "AIS-038",
                "AIS-156",
            ],
            "comparison_note": (
                "AIS-048 is battery-focused. AIS-038 addresses broader "
                "vehicle-level EV safety for applicable M/N vehicles, "
                "while AIS-156 provides L-category EV and REESS safety "
                "requirements."
            ),
        },

        "source": "ARAI AIS publication",
    },


    "AIS-049": {
        "code": "AIS-049",
        "title": (
            "Electric Power Train Vehicles — "
            "CMVR Type Approval"
        ),

        "overview": (
            "Provides the type-approval framework for battery-operated "
            "and electric power-train vehicles under the Central Motor "
            "Vehicle Rules."
        ),

        "scope": (
            "Defines technical/type-approval requirements applicable to "
            "battery-operated and electric power-train vehicles."
        ),

        "category": "EV / Type Approval",
        "vehicle_type": "Battery-operated / electric power-train vehicles",

        "purpose": (
            "To establish the technical approval pathway for electric "
            "vehicles under the applicable CMVR requirements."
        ),

        "applicability": (
            "Relevant to vehicle manufacturers and type-approval "
            "applicants seeking approval for applicable electric vehicles."
        ),

        "ev_related": True,
        "formula_available": False,
        "calculator_available": False,

        "key_requirements": [
            "Technical documentation",
            "Vehicle type approval",
            "Applicable EV test requirements",
            "Conformity with applicable AIS/CMVR provisions",
        ],

        "test_focus": [
            "Type approval",
            "Vehicle documentation",
            "Applicable vehicle-level tests",
            "Compliance verification",
        ],

        "revision_history": [
            "AIS-049",
            "AIS-049 Amendment 1",
            "AIS-049 Amendment 2",
            "AIS-049 (Rev.1)",
        ],

        "amendments": [],

        "related_standards": [
            "AIS-038",
            "AIS-039",
            "AIS-040",
            "AIS-041",
            "AIS-048",
            "AIS-053",
        ],

        "comparative_study": {
            "primary_role": "EV type-approval framework",
            "main_output": "Type-approval compliance",
            "engineering_domain": "Homologation / certification",
            "best_compared_with": [
                "AIS-038",
                "AIS-048",
            ],
            "comparison_note": (
                "AIS-049 is an approval framework, whereas AIS-038 and "
                "AIS-048 provide specific technical safety requirements. "
                "AIS-049 therefore connects applicable technical tests "
                "with the vehicle type-approval process."
            ),
        },

        "source": "ARAI AIS publication",
    },


    "AIS-053": {
        "code": "AIS-053",
        "title": "Automotive Vehicles — Types — Terminology",

        "overview": (
            "Defines vehicle types, categories and terminology used "
            "for automotive classification and regulatory application."
        ),

        "scope": (
            "Provides definitions and classifications for vehicle "
            "categories including M, N and L-category vehicles and "
            "associated terminology."
        ),

        "category": "Vehicle Classification",
        "vehicle_type": "Motor vehicles",

        "purpose": (
            "To establish consistent terminology and vehicle "
            "classification for automotive regulatory standards."
        ),

        "applicability": (
            "Used as a classification and terminology reference across "
            "vehicle approval and testing standards."
        ),

        "ev_related": True,
        "formula_available": False,
        "calculator_available": False,

        "key_requirements": [
            "Vehicle category definitions",
            "Vehicle classification",
            "Body/type terminology",
            "Category-specific terminology",
        ],

        "test_focus": [
            "Vehicle classification",
            "Category determination",
            "Regulatory terminology",
        ],

        "revision_history": [
            "AIS-053",
            "Amendments and corrigenda as published",
        ],

        "amendments": [],

        "related_standards": [
            "AIS-038",
            "AIS-040",
            "AIS-041",
            "AIS-049",
            "AIS-071",
        ],

        "comparative_study": {
            "primary_role": "Vehicle classification",
            "main_output": "Vehicle category / terminology",
            "engineering_domain": "Homologation / regulatory classification",
            "best_compared_with": [
                "AIS-049",
                "AIS-038",
                "AIS-156",
            ],
            "comparison_note": (
                "AIS-053 does not primarily prescribe a physical test. "
                "Instead, it provides the classification language that "
                "determines which vehicle-specific standards and "
                "requirements apply."
            ),
        },

        "source": "ARAI AIS publication",
    },


    "AIS-071": {
        "code": "AIS-071",
        "title": (
            "Automotive Vehicles — Identification of Controls, "
            "Tell-Tales and Indicators"
        ),

        "overview": (
            "Specifies requirements for the identification, symbols, "
            "location and recognition of vehicle controls, tell-tales "
            "and indicators."
        ),

        "scope": (
            "Covers applicable controls, tell-tales and indicators and "
            "the requirements for their identification and visibility."
        ),

        "category": "Human-Machine Interface / Vehicle Controls",
        "vehicle_type": "Motor vehicles",

        "purpose": (
            "To provide consistent and recognizable identification "
            "of vehicle controls, indicators and tell-tales for drivers."
        ),

        "applicability": (
            "Applies to vehicles and functions falling within the "
            "relevant AIS-071 parts and regulatory scope."
        ),

        "ev_related": False,
        "formula_available": False,
        "calculator_available": False,

        "key_requirements": [
            "Symbol identification",
            "Control identification",
            "Tell-tale identification",
            "Indicator identification",
            "Visibility and recognition",
        ],

        "test_focus": [
            "Symbol verification",
            "Illumination",
            "Colour",
            "Functioning",
            "Driver visibility",
        ],

        "revision_history": [
            "AIS-071 Part 1",
            "AIS-071 Part 1 (Rev.1)",
            "AIS-071 Part 2",
        ],

        "amendments": [],

        "related_standards": [
            "AIS-053",
            "AIS-004",
        ],

        "comparative_study": {
            "primary_role": "Driver information and control identification",
            "main_output": "Compliance of symbols, tell-tales and indicators",
            "engineering_domain": "Human-machine interface",
            "best_compared_with": [
                "AIS-053",
                "AIS-004",
            ],
            "comparison_note": (
                "AIS-071 addresses how vehicle controls and information "
                "are presented to the driver. AIS-053 establishes vehicle "
                "classification, while AIS-004 addresses electromagnetic "
                "compatibility of electrical/electronic systems."
            ),
        },

        "source": "ARAI AIS publication",
    },


    "AIS-137": {
        "code": "AIS-137",
        "title": (
            "Test Methods, Testing Equipment and Related Procedures "
            "for Type Approval and Conformity of Production"
        ),

        "overview": (
            "AIS-137 is a multi-part family of test methods, equipment "
            "requirements and procedures covering type approval and "
            "Conformity of Production for specified vehicle, engine "
            "and related applications."
        ),

        "scope": (
            "The individual AIS-137 parts address different vehicle "
            "categories, emission requirements, power measurement, "
            "administrative procedures and related testing."
        ),

        "category": "Testing / Type Approval / Emissions",
        "vehicle_type": "L, M, N and specified off-road / equipment categories",

        "purpose": (
            "To standardize test methodology, equipment and procedures "
            "used during approval and conformity-of-production activities."
        ),

        "applicability": (
            "Applicability depends on the specific AIS-137 part and "
            "the vehicle or engine category concerned."
        ),

        "ev_related": True,
        "formula_available": False,
        "calculator_available": False,

        "key_requirements": [
            "Standardized test procedures",
            "Testing equipment",
            "Type approval testing",
            "Conformity of Production testing",
            "Part-specific procedures",
        ],

        "test_focus": [
            "Emission testing",
            "Power measurement",
            "Vehicle category-specific tests",
            "COP testing",
            "Administrative procedures",
        ],

        "revision_history": [
            "AIS-137 Part 1 and subsequent parts",
            "Part-specific amendments and revisions",
        ],

        "amendments": [
            "AIS-137 consists of multiple parts; revision/amendment "
            "status must therefore be interpreted part-by-part."
        ],

        "related_standards": [
            "AIS-038",
            "AIS-039",
            "AIS-040",
            "AIS-041",
        ],

        "comparative_study": {
            "primary_role": "Standardized testing procedures",
            "main_output": "Test results for approval/COP",
            "engineering_domain": "Testing / homologation",
            "best_compared_with": [
                "AIS-049",
                "AIS-038",
                "AIS-039",
                "AIS-041",
            ],
            "comparison_note": (
                "AIS-137 provides testing methodology and procedures, "
                "while standards such as AIS-049 provide an approval "
                "framework and AIS-038/039/041 define specific EV "
                "technical requirements or measurements."
            ),
        },

        "source": "ARAI AIS publication",
    },


    "AIS-138": {
        "code": "AIS-138",
        "title": (
            "Electric Vehicles — Conductive Charging Requirements"
        ),

        "overview": (
            "Specifies requirements associated with conductive charging "
            "of electric vehicles, including applicable AC and DC "
            "charging arrangements."
        ),

        "scope": (
            "Covers conductive charging interfaces and related vehicle "
            "requirements through the applicable parts of AIS-138."
        ),

        "category": "EV / Charging",
        "vehicle_type": "Electric vehicles",

        "purpose": (
            "To establish requirements for safe and compatible "
            "conductive charging of electric vehicles."
        ),

        "applicability": (
            "Applicable to electric vehicles and charging arrangements "
            "within the scope of the relevant AIS-138 part."
        ),

        "ev_related": True,
        "formula_available": True,
        "calculator_available": True,

        "key_requirements": [
            "Conductive charging",
            "Charging current",
            "Electrical safety",
            "Charging interface requirements",
            "AC/DC charging provisions",
        ],

        "test_focus": [
            "AC charging",
            "DC charging",
            "Charging current",
            "Body current",
            "Earth leakage current",
        ],

        "revision_history": [
            "AIS-138 Part 1",
            "AIS-138 Part 2",
            "Applicable amendments",
        ],

        "amendments": [],

        "related_standards": [
            "AIS-038",
            "AIS-156",
            "AIS-004",
        ],

        "comparative_study": {
            "primary_role": "EV conductive charging",
            "main_output": "Charging-system compliance",
            "engineering_domain": "EV charging / electrical safety",
            "best_compared_with": [
                "AIS-038",
                "AIS-156",
            ],
            "comparison_note": (
                "AIS-138 concentrates on conductive charging. AIS-038 "
                "and AIS-156 cover broader vehicle/REESS safety. Charging "
                "requirements therefore interact with, but do not replace, "
                "the broader EV electrical-safety requirements."
            ),
        },

        "source": "ARAI AIS publication",
    },


    "AIS-156": {
        "code": "AIS-156",
        "title": (
            "Specific Requirements for L Category Electric "
            "Power Train Vehicles"
        ),

        "overview": (
            "Specifies electrical safety and rechargeable electrical "
            "energy storage system safety requirements for L-category "
            "electric power-train vehicles."
        ),

        "scope": (
            "Contains Part I requirements for vehicle electrical safety "
            "and Part II requirements for the safety of the rechargeable "
            "electrical energy storage system (REESS)."
        ),

        "category": "EV / L-Category Safety",
        "vehicle_type": "L-category electric power-train vehicles",

        "purpose": (
            "To establish specific safety requirements for electric "
            "two- and three-wheeler power trains and their REESS."
        ),

        "applicability": (
            "Applicable to L-category electric power-train vehicles "
            "within the defined regulatory scope."
        ),

        "ev_related": True,
        "formula_available": False,
        "calculator_available": False,

        "key_requirements": [
            "Vehicle electrical safety",
            "REESS safety",
            "Protection against direct contact",
            "Electrical isolation",
            "BMS-related requirements",
            "REESS ingress protection",
        ],

        "test_focus": [
            "Electrical isolation",
            "Electric shock protection",
            "REESS safety",
            "Water ingress / IP testing",
            "BMS protection",
        ],

        "revision_history": [
            "AIS-156",
            "Amendment 1",
            "Amendment 2",
            "Amendment 3",
        ],

        "amendments": [
            "Amendments have introduced additional requirements including "
            "battery/BMS safety and REESS-related protections."
        ],

        "related_standards": [
            "AIS-038",
            "AIS-048",
            "AIS-138",
            "AIS-004",
        ],

        "comparative_study": {
            "primary_role": "L-category EV safety",
            "main_output": "Vehicle and REESS safety compliance",
            "engineering_domain": "Electric two/three-wheelers",
            "best_compared_with": [
                "AIS-038",
                "AIS-048",
            ],
            "comparison_note": (
                "AIS-156 is the L-category counterpart within this "
                "project's EV safety set. AIS-038 addresses the applicable "
                "M/N electric vehicle safety framework, while AIS-048 "
                "focuses specifically on traction batteries."
            ),
        },

        "source": "ARAI AIS publication",
    },


    "AIS-189": {
        "code": "AIS-189",
        "title": (
            "Approval of Vehicles with Regard to Cyber Security "
            "and Cyber Security Management System"
        ),

        "overview": (
            "Defines vehicle cybersecurity approval requirements and "
            "the Cyber Security Management System (CSMS) processes "
            "required from relevant vehicle manufacturers."
        ),

        "scope": (
            "Addresses cybersecurity risks across relevant vehicle "
            "development, production and post-production activities "
            "and requires an organizational cybersecurity management "
            "approach."
        ),

        "category": "Cybersecurity / Connected Vehicles",
        "vehicle_type": "Connected and electronically controlled vehicles",

        "purpose": (
            "To establish a systematic cybersecurity-management "
            "framework for identifying, assessing and mitigating "
            "vehicle cybersecurity risks."
        ),

        "applicability": (
            "Relevant to vehicle manufacturers and vehicle types "
            "covered by the applicable cybersecurity approval framework."
        ),

        "ev_related": False,
        "formula_available": False,
        "calculator_available": False,

        "key_requirements": [
            "Cyber Security Management System",
            "Risk assessment",
            "Threat analysis",
            "Risk mitigation",
            "Organizational cybersecurity processes",
            "Security throughout vehicle lifecycle",
        ],

        "test_focus": [
            "Cybersecurity processes",
            "Threat and risk assessment",
            "Security controls",
            "Evidence of CSMS implementation",
            "Vehicle cybersecurity assessment",
        ],

        "revision_history": [
            "AIS-189",
            "Interpretation Manual for AIS-189",
        ],

        "amendments": [],

        "related_standards": [
            "AIS-190",
        ],

        "comparative_study": {
            "primary_role": "Vehicle cybersecurity governance",
            "main_output": "CSMS / cybersecurity approval",
            "engineering_domain": "Automotive cybersecurity",
            "best_compared_with": [
                "AIS-190",
            ],
            "comparison_note": (
                "AIS-189 governs cybersecurity and CSMS. AIS-190 addresses "
                "software updates and SUMS. Together they cover two related "
                "but distinct lifecycle-security areas: cybersecurity "
                "management and controlled software-update management."
            ),
        },

        "source": "ARAI AIS publication",
    },


    "AIS-190": {
        "code": "AIS-190",
        "title": (
            "Approval of Vehicles with Regard to Software Update "
            "and Software Update Management System"
        ),

        "overview": (
            "Defines requirements for vehicle software-update approval "
            "and the Software Update Management System (SUMS)."
        ),

        "scope": (
            "Covers organizational and technical processes associated "
            "with software updates, including update identification, "
            "impact assessment, delivery, verification and records."
        ),

        "category": "Software / Connected Vehicles",
        "vehicle_type": "Vehicles with updateable electronic systems",

        "purpose": (
            "To ensure software updates are managed in a controlled, "
            "traceable and safe manner throughout the vehicle lifecycle."
        ),

        "applicability": (
            "Relevant to vehicle manufacturers and updateable vehicle "
            "systems within the applicable software-update approval scope."
        ),

        "ev_related": False,
        "formula_available": False,
        "calculator_available": False,

        "key_requirements": [
            "Software Update Management System",
            "Software identification",
            "Configuration control",
            "Update impact assessment",
            "Update authenticity and integrity",
            "Verification and validation",
            "Update records",
        ],

        "test_focus": [
            "Software-update process",
            "Update integrity",
            "Update authenticity",
            "Impact assessment",
            "Verification and validation",
            "OTA/update mechanisms where applicable",
        ],

        "revision_history": [
            "AIS-190",
            "Interpretation Manual for AIS-190",
        ],

        "amendments": [],

        "related_standards": [
            "AIS-189",
        ],

        "comparative_study": {
            "primary_role": "Software-update governance",
            "main_output": "SUMS / software-update approval",
            "engineering_domain": "Automotive software",
            "best_compared_with": [
                "AIS-189",
            ],
            "comparison_note": (
                "AIS-190 focuses on controlled software updates and SUMS, "
                "while AIS-189 focuses on cybersecurity and CSMS. A modern "
                "connected vehicle may need to satisfy both frameworks."
            ),
        },

        "source": "ARAI AIS publication",
    },
}